# -------------------------------------------------------------
# This program uses an open-source LLM running locally via Ollama
# Ollama acts like an OpenAI-compatible server on your machine
# -------------------------------------------------------------

from openai import OpenAI

# Create a client that talks to Ollama instead of OpenAI cloud
# base_url points to Ollama's local server
ollama = OpenAI(
    base_url='http://localhost:11434/v1',
    api_key='ollama'  # Dummy key; Ollama does not need a real API key
)

# Name of the local model we want to use
model_name = "llama3.2:latest"

# -------------------------------------------------------------
# STEP 1: Ask Ollama to generate a challenging IQ question
# -------------------------------------------------------------

# This is the instruction we want to give the model
question = "Please propose a hard, challenging question to assess someone's IQ. Respond only with the question."

# Messages are sent as a conversation
# Here, we send only one user message
messages = [
    {
        "role": "user",
        "content": question
    }
]

# Send the request to Ollama and get a response
response = ollama.chat.completions.create(
    model=model_name,
    messages=messages
)

# Extract the question generated by the model
question = response.choices[0].message.content

# Display the question generated by Ollama
print(f"Ollama Question: {question}")

# -------------------------------------------------------------
# STEP 2: Send the generated question back to Ollama
#         and ask it to answer its own question
# -------------------------------------------------------------

# Now we reuse the generated question as a new user input
messages = [
    {
        "role": "user",
        "content": question
    }
]

# Ask the model to respond again
response = ollama.chat.completions.create(
    model=model_name,
    messages=messages
)

# Extract the answer from the model's response
answer = response.choices[0].message.content

# Display the answer generated by Ollama
print(f"Ollama Answer: {answer}")
