name: Update fork PRs

on:
  schedule:
    - cron: "0 6 * * *" # Cada día a las 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  autoupdate:
    runs-on: ubuntu-latest

    steps:
      - name: autoupdate-fork-action
        uses: Shurtu-gal/autoupdate-fork-action@v1.0.1
        with:
          github_token: ${{ secrets.BOT_TOKEN }}
          base_branches: main
          pr_filter: all
          merge_fail_action: comment
          merge_method: merge
          ignore_conflicts: true
